### ISSUE TITLE
before CRAN todo

### ISSUE THREAD

**Issue by kasiapekala** [ModelOriented/triplot#13]
- [x]  readme - remove collapsible sections
- [x] aspect_importance() - switch order of parameters sample_method and n_var
- [x] remove ` == 1` in glm model for titatnic
- [x] check predict_aspects() for titanic glm results (readme)
